### PR TITLE
New variable `CHUNKED_UPLOAD_USE_TEMP_STORAGE` for making the plugin …

### PR DESCRIPTION
**Pull request by GitRon**
New variable to enable usage for django projects in the cloud.

### CODE REVIEW

**Comment by GitRon** [comment]
@jerinpetergeorge I could bump the version to 2.1.0 and add the stuff in the changelog?

**Comment by jerinpetergeorge** [comment]
@GitRon 
First of all, can you clarify the usage of your suggestion? How does this help in AWS upload?


Apart from that, I wish to follow the below pattern for settings variable,
**`DJANGO_CHUNK_UPLOAD_<Variable_Name>`**. So, Change `CHUNKED_UPLOAD_USE_TEMP_STORAGE` to something like **`DJANGO_CHUNK_UPLOAD_USE_TEMP_STORAGE`**.

**Comment by GitRon** [comment]
@jerinpetergeorge Well, currently the file chunks are written to the target. If you use an object storage like S3 you cannot write or read files from there. You can only move whole files with requests.

Good suggestion about the var name. I'll do this right now.

**Comment by GitRon** [comment]
@jerinpetergeorge You should write a bit in the readme if you want to migrate from the old package to yours. For example the renamed variables.

**Comment by GitRon** [comment]
@jerinpetergeorge Did you see my question in the review? any more open questions about the usefulness of my idea?

**Comment by jerinpetergeorge** [comment]
I wish I could. But, I didn't test the PR, did you test? @GitRon

**Comment by GitRon** [comment]
@jerinpetergeorge sorry for the late reply! busy sprint... 😅 
please have a look at my question in the PR, then we can finish this :)
i use this code in 2-3 projects and it works, so i think this should be prove enough.
if we get this in your package I'll blog about it in my new company blog and make some advertisment for the package ;)

**Comment by jerinpetergeorge** [comment]
Can we release our next version? Do you have any other suggestions?

**Comment by GitRon** [comment]
Thanks, I'll check it out and see if it works.

**Comment by GitRon** [comment]
Ok, found the first issue. You have a new PR for this.

Secondly, because you renamed all the `chunked` to `chunk` we should write an upgrade guide from the original package. Or did you do something like this already?

**Comment by jerinpetergeorge** [comment]
I have already created an issue for migration purpose, #7. But, I didn't start that yet. Can you do it? @GitRon

**Comment by GitRon** [comment]
@jerinpetergeorge I saw that you renamed all the classes and variables from `chunked` to `chunk`. This creates lots of overhead for upgraders. Maybe we should stick to the original class names?

**Comment by GitRon** [comment]
@jerinpetergeorge I tested my solution - it works! You can release a new version if you like. Then I can use it properly in my projects!

**Comment by jerinpetergeorge** [comment]
@GitRon What about the migration guide? I'm bit confused :(

**Comment by GitRon** [comment]
@jerinpetergeorge I see two ways:

1) I wrote a comment in issue #7 what to do. You put this in the readme and we are good to go.
2) You revert all the chunked-to-chunk changes in methods, variables and class names, so upgrades just need to change the package in the settings, requirements and imports. Way faster. 

But it's your package and you have to decide 😄

**Pull request merged**
